services:
  web:
    build: .
    container_name: timeline-api
    
    ports:
      - "8000:8000"

    env_file:
      - ./.env

    volumes:
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped

