[project]
name = "chrono-guess-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "django~=6.0.0",
    "django-cors-headers>=4.9.0",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.11",
]
